name: Docker Deploy

on: workflow_dispatch

jobs:
  run-deploy:
    uses: powsybl/github-ci/.github/workflows/manual-dockerdeploy-backend-app-generic.yml@c81718897ef649fcdc685955a094bf724bf7fa9e
    with:
      dockerImage: docker.io/powsybl/single-line-diagram-server
      dockerUsername: powsyblci
    secrets:
      DOCKER_RELEASE: ${{ secrets.DOCKER_RELEASE }}
