name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout network store sources
        uses: actions/checkout@v1
        with:
          repository: powsybl/powsybl-network-store
          ref: refs/heads/master

      - name: Build and install network store client with Maven
        run: mvn --batch-mode -Pclient install

      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Build with Maven
        run: mvn --batch-mode package

      - name: Run SonarCloud analysis
        if: matrix.os == 'ubuntu-latest'
        run: >
          mvn --batch-mode -Pjacoco package sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=powsybl-ci-github
          -Dsonar.projectKey=com.powsybl:powsybl-single-line-diagram-server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
